### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Harshu467** [SamarthKadam/ChatBox#10]
Create Footer to add links and socials

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by deepak9285** [comment]
Hello would be happy to help with the issue . Could you please assign it to me

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me 
@Harshu467
