### ISSUE TITLE
Mic button in the chat section is malfunctioning

### ISSUE THREAD

**Issue by mondalsurojit** [SamarthKadam/ChatBox#103]
### Describe the bug

The Mic button is getting displaced, when clicked and also there is no proper indicator for how long the audio is recorded.

### Add ScreenShots

![Screenshot (264)](https://github.com/SamarthKadam/ChatBox/assets/114282267/4729c8d8-96dc-48e9-b4b9-c532969d7c9a)
![Screenshot (265)](https://github.com/SamarthKadam/ChatBox/assets/114282267/e6d2301b-165b-4c02-a270-be5740bd2747)

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SamarthKadam** [comment]
@mondalsurojit  Yes you can work on it.
