### ISSUE TITLE
dark mode | add a dark mode enable/disable option

### ISSUE THREAD

**Issue by lavkeshmeena015** [SamarthKadam/ChatBox#119]
add a dark mode enable or disable option

**Comment by 2305e3ish** [comment]
#souravbhunia07 i would like to add dark mode feauture.please assign this to me under GSSoC'24.
Also many issues don't have labels to them.

**Comment by souravbhunia07** [comment]
Hi @lavkeshmeena015 I have assigned this issue to you.
Happy Coding!

**Comment by Dark-S8uL** [comment]
@souravbhunia07 I want to include the dark mode feature. Kindly assign this task to me under GSSoC'24.

**Comment by lavkeshmeena015** [comment]
Hii @souravbhunia07 
Thank you for assigning this issue to me. I'll look into it right away and provide updates as I make progress.

**Comment by souravbhunia07** [comment]
> @souravbhunia07 I want to include the dark mode feature. Kindly assign this task to me under GSSoC'24.

Already assigned!
