### ISSUE TITLE
Bug On SignUp page it should seen like SignUp with Google as it is written Sign In with google

### ISSUE THREAD

**Issue by Harshu467** [SamarthKadam/ChatBox#12]
Bug On SignUp page it should seen like SignUp with Google as it is written Sign In with google

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by Isha1233** [comment]
@SamarthKadam kindly assign this task to me
