### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [SamarthKadam/ChatBox#122]
Currently, there is no issue template for this repo, so I want to add it which will look like this 👇

![image](https://github.com/SamarthKadam/ChatBox/assets/73957207/35f8936c-f35a-4010-a527-d2c3ff6fa0fa)

- Also I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/SamarthKadam/ChatBox/assets/73957207/e40ec16b-030e-4888-b5ce-5fead52e14b5)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by Saigenix** [comment]
go on!

**Comment by TonyStark-47** [comment]
Hey @Saigenix, I have raised a PR #135 related to this issue. Please check it out.
