### ISSUE TITLE
Message Reaction - add reactions to the chats

### ISSUE THREAD

**Issue by Nikitakandwal** [SamarthKadam/ChatBox#124]
I want to contribute to the project as a GSSOC contributor by adding reaction functionality to the texts, making the conversation more interesting and fun.

**Comment by lavkeshmeena015** [comment]
@SamarthKadam  please mark the label for this issue

**Comment by Saigenix** [comment]
Hey @Nikitakandwal! Can you please explain the steps for implementing this feature?

**Comment by Nikitakandwal** [comment]
Absolutely! I've completed the frontend implementation, and I'm currently working on integrating the backend. I'll need some additional time to integrate the backend components. 
Here's a screenshot of frontend to show how it will be displayed on frontend part.
![screenshot-reaction](https://github.com/SamarthKadam/ChatBox/assets/98966392/a0c211a3-3d3a-4c5f-a836-954b63d3621b)

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
