### ISSUE TITLE
Auto Commenting when a PR is merged

### ISSUE THREAD

**Issue by suhanipaliwal** [SamarthKadam/ChatBox#134]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by souravbhunia07** [comment]
Hi @suhanipaliwal , Could you please provide more details on your approach to tackling this task?

**Comment by suhanipaliwal** [comment]
I will be adding a YAML file in the .github directory to define this workflow of auto commenting on the trigger of a pull request being merged

**Comment by souravbhunia07** [comment]
Hi @suhanipaliwal , I have assigned this issue to you.
Happy Coding!
