### ISSUE TITLE
favicon image

### ISSUE THREAD

**Issue by SuryanshuKushwaha** [SamarthKadam/ChatBox#140]
Favicon image is different from image on website page , please assign me this issue and tag under GSSOC 2024 @SamarthKadam 
![Screenshot (40)](https://github.com/SamarthKadam/ChatBox/assets/114632428/1459add3-f99b-46f0-ad44-b8831718b5a6)

**Comment by souravbhunia07** [comment]
Hi @SuryanshuKushwaha , I have assigned this issue to you.
Happy Coding!
