### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by Harshu467** [SamarthKadam/ChatBox#15]
Send Media like Share photo , video

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀
