### ISSUE TITLE
Typographical Errors & Clarifications

### ISSUE THREAD

**Issue by Zoha-Waheed** [SamarthKadam/ChatBox#163]
There are some typos in README like Comin soon & some commands are missing under contribution guidelines.

ASSIGN THIS ISSUE TO ME (as gssoc contributor).

**Comment by souravbhunia07** [comment]
Hi @Zoha-Waheed , I have assigned this issue to you. If you get into any error feel free to ask.

**Comment by Zoha-Waheed** [comment]
> Hi @Zoha-Waheed , I have assigned this issue to you. If you get into any error feel free to ask.

Gracias, I will be soon back with PR.

**Comment by Zoha-Waheed** [comment]
> Hi @Zoha-Waheed , I have assigned this issue to you. If you get into any error feel free to ask.

PR has been sent, please authorize on vercel and merge.

**Comment by Zoha-Waheed** [comment]
Issue has been resolved.
