### ISSUE TITLE
Markdown Syntax for Code Blocks

### ISSUE THREAD

**Issue by Zoha-Waheed** [SamarthKadam/ChatBox#164]
Assign this issue to me.

Proper documentation of code blocks is required to make readability more clear.

**Comment by souravbhunia07** [comment]
Hi @Zoha-Waheed , I have assigned this issue to you. If you get into any error feel free to ask.

**Comment by mahek0620** [comment]
@SamarthKadam can i work on this , I can complete this within a day

**Comment by Zoha-Waheed** [comment]
> Hi @Zoha-Waheed , I have assigned this issue to you. If you get into any error feel free to ask.

For sure.
Thanks a lot for it.

**Comment by Zoha-Waheed** [comment]
> Hi @Zoha-Waheed , I have assigned this issue to you. If you get into any error feel free to ask.

Pull Request has been sent, please authorize on vercel and merge

**Comment by Zoha-Waheed** [comment]
Issue has been resolved.
