### ISSUE TITLE
Bio Section

### ISSUE THREAD

**Issue by Harshu467** [SamarthKadam/ChatBox#17]
Create Section in Setting to add Bio to profile

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by DownOnCoffee** [comment]
I will add a section in profile page/setting to add a bio to profile.
Please assign this task to me. I am an experienced frontend developer. I can do this task in a short time.
