### ISSUE TITLE
Improve Error Handling and useEffect Dependency in HomeChat.js

### ISSUE THREAD

**Issue by SamFusedBits** [SamarthKadam/ChatBox#178]
In the HomeChat.js file, there are a few areas that could be improved for better code quality and error handling:

- Error Handling: In the getAllChats function, there is no error handling for the fetch request. If the request fails for any reason, the application might crash or behave unexpectedly. We should add a try-catch block to handle any potential errors.

- Dependency Array in useEffect: In the useEffect hook, we have dispatch as a dependency. If the dispatch function changes for any reason, the effect will run again. However, dispatch function from useDispatch hook will not change across re-renders. So, we can safely remove it from the dependencies array.

**Comment by souravbhunia07** [comment]
Hi @SamFusedBits , I have assigned this task to you. If you face any difficulties feel free to ask.
Happy Coding!
