### ISSUE TITLE
Group Profile Change

### ISSUE THREAD

**Issue by Harshu467** [SamarthKadam/ChatBox#19]
There should be feature to change profile for Group

**Comment by Harshu467** [comment]
My self Harsh Upadhye , I have participated in GSOC 23 last year, I have good experience of working on open source projects. Please Assign this to me

**Comment by abhiperfect** [comment]
Subject: Add functionality: Group Profile Change

Hi,

I hope this message finds you well.

Issue: Adding functionality so group profile can change.

I have been working on a similar project, which you can find on my GitHub, so I believe I can offer valuable assistance in resolving this issue.

Could you please assign this task to me so I can investigate and resolve the issue promptly? I'm confident I can provide insights and contribute effectively to fixing this bug.

Looking forward to your response.

Best regards,
Abhishek Prajapati
