### ISSUE TITLE
Make a 404 not found page

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [SamarthKadam/ChatBox#218]
Make a 404 not found page for your website

**Comment by RamakrushnaBiswal** [comment]
hi @souravbhunia07 i want to work upon it can you assign it to me/

**Comment by RamakrushnaBiswal** [comment]
its looks like this 
![image](https://github.com/SamarthKadam/ChatBox/assets/125277258/508f2611-3142-41ee-b23f-074768ed8d8e)

**Comment by souravbhunia07** [comment]
Hi @RamakrushnaBiswal , I have assigned this issue to you. Please add some styling also.
Happy Coding!

**Comment by RamakrushnaBiswal** [comment]
hi @souravbhunia07 thank you for assigning me, I will try my best to do this ,can you increase it to label 2 ?🥹

**Comment by RamakrushnaBiswal** [comment]
issue solved PR #230
