### ISSUE TITLE
Implementing Password Reset Functionality Using Nodemailer

### ISSUE THREAD

**Issue by Prateek579** [SamarthKadam/ChatBox#223]
I will develop a robust password reset functionality using Node.js and Nodemailer. This feature will enhance user experience and security by allowing users to securely reset their passwords via email.

Send Reset Email: Using Nodemailer, an email containing the password secret code will be sent to the user's registered email address.

Password Update: If the secret code is valid, users will be prompted to enter a new password, which will be securely updated in the database.

@SamarthKadam please assign this issue to me.

**Comment by souravbhunia07** [comment]
Hi @Prateek579 , I have assigned this issue to you.
Happy Coding!
