### ISSUE TITLE
Adding FAQ section at the home page

### ISSUE THREAD

**Issue by MuraliDharan7** [SamarthKadam/ChatBox#232]
I want to add FAQ section in the home which will provide the information to users what is this product doing and some other questions as well.

![image](https://github.com/SamarthKadam/ChatBox/assets/130668745/3c4875b7-f336-4485-8f4c-6fed00b448d8)

Please assign this to me under GSSoC'24. Add relevant labels into it.

**Comment by souravbhunia07** [comment]
Hi @MuraliDharan7 , I have assigned this issue to you. 
Happy Coding!
