### ISSUE TITLE
Multiple Section, Modern Desing for Landing Page

### ISSUE THREAD

**Issue by satyam8932** [SamarthKadam/ChatBox#235]
Hi @SamarthKadam I want to work on this issue.

I will add Multiple Section, Modern Desing for Landing Page which will show various options and features regarding the application like the services provides, pricing, resources and many other things.

Enhancement in the UI design and modern design using extensive assets.

Please assign me this issue with GSSOC and level 3 labels as this will be bigger projects with multiple changes for the landing page.

Thanks
Satyam

**Comment by SamarthKadam** [comment]
@satyam8932 We don't have any pricing , resource stuff for this app. Please look for the different issues

**Comment by satyam8932** [comment]
can you assign me this issue
https://github.com/SamarthKadam/ChatBox/issues/234
