### ISSUE TITLE
Signup page doesn't work

### ISSUE THREAD

**Issue by DownOnCoffee** [SamarthKadam/ChatBox#24]
After the user enters his/her information in signup page , you get a toast "something went wrong" .
Same toast you get when you try to signup with Google.

**Comment by SamarthKadam** [comment]
Can I get to know more about this exactly?

**Comment by Ansh101112** [comment]
actually there are issues in authentication as on every kind of error during auth like email not found password is incorrect everytime you will get the same error response of something went wrong so i want to work on this issue to fix this authentication part 
@SamarthKadam sir please assign me this issue to start working on it

**Comment by anwesha2002** [comment]
@SamarthKadam 
I am a GSSOC'24 contributor . Can you assign this to me . I would like to work on this.
