### ISSUE TITLE
Signup page - Add Password Requirements below Form

### ISSUE THREAD

**Issue by ShreeluSantosh** [SamarthKadam/ChatBox#243]
## Issue
In the signup page, while entering the password, if the password does not meet any of the requirements, we get a red pop-up alert. 

This current feature can be annoying to some users, who are not aware of the password requirements. 

## Screenshots
<ul>
<li>
password length <br>
<img src="https://github.com/SamarthKadam/ChatBox/assets/94289402/15e2eb30-b0a8-49cb-a8c8-48247d70785b" height="350"/>
</li>
<li>
number <br>
<img src="https://github.com/SamarthKadam/ChatBox/assets/94289402/6337fa69-fa09-4ee3-9d09-15100c2bada0" height="350"/>
</li>
<li>
uppercase letter <br>
<img src="https://github.com/SamarthKadam/ChatBox/assets/94289402/341f1670-8fd6-4e66-be83-b3fd05b9e092" height="350"/>
</li>
</ul>

## Solution
Add a small card below the form displaying the password requirements so that the user can set their new password accordingly. 

This will improve user experience.

## Program

GSSOC

**Comment by AnupamSingh2004** [comment]
I can Fix this issue
Please assign me this issue under GSSOC

**Comment by Shubham-Zone** [comment]
@SamarthKadam please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by souravbhunia07** [comment]
Hi @ShreeluSantosh , I have assigned this issue to you if you get any confusion feel free to ask. 
Happy Coding!

**Comment by ShreeluSantosh** [comment]
PR linked: #257

**Comment by ShreeluSantosh** [comment]
New PR Linked: #258
