### ISSUE TITLE
Automatic Comment on Pull Request Raised

### ISSUE THREAD

**Issue by thevijayshankersharma** [SamarthKadam/ChatBox#275]
Often, when pull requests (PRs) are raised, reviewers may lack crucial context about the changes proposed. This can lead to delays in the review process and misunderstandings between contributors and reviewers.

**Comment by souravbhunia07** [comment]
Hi @thevijayshankersharma can you please explain more, and give a little idea of how can you implement this?

**Comment by thevijayshankersharma** [comment]
@souravbhunia07 Now when ever someone Raise the PR then there is not greeting message for it. I would like to add it.
Then there are many things which are missing in workflow like greeting on issue or PR closed, auto close of old issues and PRs, greeting on PR got merge. If you need any of these tell me. I would like to do it.

**Comment by techmannih** [comment]
@souravbhunia07  assigned
