### ISSUE TITLE
Unresponsive on smaller screens

### ISSUE THREAD

**Issue by The-Phoenics** [SamarthKadam/ChatBox#281]
The current layout of the application overflows/breaks on smaller screen sizes

![msg](https://github.com/SamarthKadam/ChatBox/assets/96228962/31807384-b895-45e5-9866-a208c03f6ce6)
![search](https://github.com/SamarthKadam/ChatBox/assets/96228962/0c9081b9-e52f-4f3c-a04f-8a1b8d9ba7e5)

### Screenshots
![info](https://github.com/SamarthKadam/ChatBox/assets/96228962/c4da47e4-07e6-49c3-811e-0bd7a58c67b2)

**Comment by The-Phoenics** [comment]
Hey @SamarthKadam 
I would like to work on this for GSSoC'24.

**Comment by Saigenix** [comment]
This is important fix please work properly! I will assign to you

**Comment by The-Phoenics** [comment]
Sure! You can assign this to me @Saigenix :)
