### ISSUE TITLE
The Node Modules are Getting pushed into the Codebase

### ISSUE THREAD

**Issue by ROKUMATE** [SamarthKadam/ChatBox#284]
<img width="1257" alt="Screenshot 2024-06-25 at 7 04 30 PM" src="https://github.com/SamarthKadam/ChatBox/assets/77058883/7b3213a6-8071-425e-8300-427f94b2ce2c">
i would add a .gitignore file into both the backend and the frontend ... so it will be easy to redirect and delete the nodemodules getting pushed into the code base 

I am a GSSOC contributor so if u assign me do add the label to it

**Comment by Spiral-Memory** [comment]
Hey @ROKUMATE Assigned it to you, please fix it
