### ISSUE TITLE
login and signup page responsiveness

### ISSUE THREAD

**Issue by Ketanop321** [SamarthKadam/ChatBox#287]
Your responsiveness is good but when it comes to 14inches laptop like mine(hp14s) , it is not getting fitted in screen, we have to make responsive design of your navbar on every screen and  Check CSS for Media Queries.

https://github.com/SamarthKadam/ChatBox/assets/146806880/238f2dd6-be53-4c25-975e-f646fbf42d6a

**Comment by Saigenix** [comment]
Good you noticed that can you find more such issues then try to combine them all and include in this issue

**Comment by Aman0474** [comment]
I would like to work on this issue i have understood the problem statement and will provide the optimal solution for it

**Comment by malhotramoulie** [comment]
Hi
Can u pls assign me this 
I would like to solve the issue

**Comment by Saigenix** [comment]
> Hi Can u pls assign me this I would like to solve the issue

Collect more similar issues and create one issue with it

**Comment by malhotramoulie** [comment]
ok sir

**Comment by Gamerking177** [comment]
pls assign me
