### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by SamarthKadam** [SamarthKadam/ChatBox#31]
In the LoginPage and the SignUp Page. When the page size comes down from 800px try to make it responsive and good in design
![Screenshot 2024-05-11 171702](https://github.com/SamarthKadam/ChatBox/assets/87573175/00fd6ab7-d503-4ef0-8324-7e27900d74c0)

**Comment by Sky-De** [comment]
@SamarthKadam hi there, please assign this to me

**Comment by Sky-De** [comment]
@SamarthKadam thanks for the assignment, your app got stuck on an infinite loop of the loading phase, is there anything that can help here?

**Comment by Sky-De** [comment]
@SamarthKadam thanks for the assignment, please provide .env.example for both frontend and backend, I am looking forward for those files , then I will start fixing issues, thanks

**Comment by abhishek7088** [comment]
please assign this problem to me I will try to make the design better than the current .

**Comment by SamarthKadam** [comment]
@Sky-De  please look on the docs

**Comment by rishabht10** [comment]
please assign it to me
