### ISSUE TITLE
Feat: Add a button to send emojis. 

### ISSUE THREAD

**Issue by PradeepKundekar0101** [SamarthKadam/ChatBox#4]
<img width="746" alt="Screenshot 2024-02-09 at 9 51 46 AM" src="https://github.com/SamarthKadam/ChatBox/assets/91021094/3eea37cd-22f8-44d0-b554-b13910a44677">

Allowing the use of emojis in chats would give users the ability to better express their emotions.
You can use this npm package to implement the same.

**Comment by SamarthKadam** [comment]
Yeah thought to add it but we have this windows+. option to open emoji input. But Yeah soon will add it

**Comment by PradeepKundekar0101** [comment]
Yeah, because not every user knows about this shortcut
