### ISSUE TITLE
ADD AN ALERT ON BEFORE UPLOADING PICTURE

### ISSUE THREAD

**Issue by Ansh101112** [SamarthKadam/ChatBox#5]
### Description:
Currently, when users upload an image for their profile picture, there's no confirmation step. This can lead to unintentional uploads or mistakes. To enhance user experience and prevent accidental changes, we should implement a confirmation alert that prompts users to confirm their action before the image is uploaded as their profile picture.

### Tasks:
1. Implement a JavaScript function to display a confirmation modal when users attempt to upload a profile picture.
2. The modal should include a message asking users to confirm their action.
3. Provide "Confirm" and "Cancel" buttons within the modal.
4. If the user confirms, proceed with the upload process; otherwise, cancel the upload action.
5. Ensure that the modal is visually appealing and easy to understand.
6. Test the functionality thoroughly to ensure it works as expected on all supported devices and browsers.

### Acceptance Criteria:
- When a user clicks on the "Upload" button for their profile picture, a confirmation modal should appear.
- The modal should display a clear message asking the user to confirm their action.
- The modal should have "Confirm" and "Cancel" buttons.
- If the user clicks "Confirm," the image upload process should proceed as usual.
- If the user clicks "Cancel," the upload action should be canceled, and the user should remain on the same page without any changes.

### Additional Information:
- Consider accessibility guidelines to ensure that the modal is accessible to all users, including those using screen readers or keyboard navigation.
- It's important to maintain a seamless user experience while adding this confirmation step. The modal should not disrupt the flow of the upload process but rather enhance it by providing clarity and control to the user.
- If there are any design considerations or constraints, please provide them so that they can be taken into account during implementation.

**Comment by Ansh101112** [comment]
Hello @SamarthKadam I am a gssoc'24 contributor and want to work on this project could you assign me this issue to start working on it?

**Comment by SamarthKadam** [comment]
Ok but before that please share me the design of the model. Keep it more syncrhonized with the application

**Comment by Ansh101112** [comment]
@SamarthKadam sir how to run this web application in our local machine?? I have run the frontend code but the loader is running continuously and not showing anything further is it due to backend server not running? if yes then sir i will add my own env variables to run the backend server is it correct approach?

**Comment by SamarthKadam** [comment]
@Ansh101112 I'll update the docs

**Comment by Ansh101112** [comment]
okay, sir and currently getting this error from the socket.io
![Screenshot (51)](https://github.com/SamarthKadam/ChatBox/assets/87803348/daf3280e-900a-4eed-bc75-3e1d875b6639)

**Comment by SamarthKadam** [comment]
Hey @Ansh101112 I've added steps for skipping backend setup in the docs go through it.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Ansh101112** [comment]
@IP80808080 working on this issue. Please see other issue.

**Comment by Ansh101112** [comment]
@SamarthKadam sir could you please add the GSSOC badge and level of difficulty on this issue? So that I can raise the pr for this issue as I have worked on it.

**Comment by Ansh101112** [comment]
ISSUE RESOLVED
