### ISSUE TITLE
 Improve Error Handling for Signup/Login Process

### ISSUE THREAD

**Issue by Ramu-chiluveru** [SamarthKadam/ChatBox#50]
Currently, when users attempt to sign up or log in to our system, there is a lack of detailed error messages provided in case of failures. This results in a poor user experience as users are left unsure about what went wrong, making it challenging for them to troubleshoot and resolve the issue.

Issue Details:
Inadequate Error Messages: The error messages displayed during the signup/login process are generic and do not provide specific details about the nature of the error. Users are often left with messages such as "Something went wrong" or "Error occurred," which are not helpful in identifying the underlying issue.

User Confusion: Due to the lack of informative error messages, users may become frustrated and confused when they encounter errors during the signup/login process. This can lead to abandonment of the signup/login flow, resulting in a loss of potential users.

Difficulty in Troubleshooting: Without clear error messages, users have difficulty understanding what went wrong and how to resolve the issue. This can increase the burden on customer support as users may reach out for assistance in identifying and fixing the problem.

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributor. I want to work on this issue. So, I request to assign this to me.
@SamarthKadam

**Comment by SamarthKadam** [comment]
Yeah I tried it but somtimes backend doesn't responn with meaningful messages So keeping it as it is @Ramu-chiluveru
