### ISSUE TITLE
Adding Anonymous Chat Mode

### ISSUE THREAD

**Issue by mahek0620** [SamarthKadam/ChatBox#57]
adding a feature where we can chat with others without anyone knowing who you are.. It'll be like having secret conversations in a safe space. This way, you can talk openly and honestly without worrying about revealing your identity

**Comment by Isha1233** [comment]
@mahek0620  kindly assign this task to me. For implement a secret chat , I will design a simple UI for chat input and display. I will use Firebase for authentication and real-time database. Enable Firebase Authentication for anonymous sign-in, assign random identifiers to users, and handle messages securely.

**Comment by mahek0620** [comment]
@SamarthKadam please assign this task to me

**Comment by SamarthKadam** [comment]
Well the idea doesn't fit in lookout for some other issues
