### ISSUE TITLE
Improve the UI of the navbar for mobile view

### ISSUE THREAD

**Issue by parikhitritgithub** [SamarthKadam/ChatBox#6]
Hello @SamarthKadam  i want to improve your ui of  navbar  in  mobile view  .  i also have demo what i want to do 

![Screenshot 2024-05-10 005542](https://github.com/SamarthKadam/ChatBox/assets/124444610/36656566-2e36-4956-a421-62a560f07e96)

![Screenshot 2024-05-10 005707](https://github.com/SamarthKadam/ChatBox/assets/124444610/eabaecf9-a512-4d63-899c-0fbf86624bff)
![Screenshot 2024-05-10 005801](https://github.com/SamarthKadam/ChatBox/assets/124444610/0161aff2-eee7-4885-94ae-eb91daf1c248)

                                                     Can you please assign this to me

**Comment by SamarthKadam** [comment]
Can you please elaborate with the design

**Comment by parikhitritgithub** [comment]
![Screenshot 2024-05-10 131307](https://github.com/SamarthKadam/ChatBox/assets/124444610/3e75829b-6636-4662-8f75-7374ab347f79)


I just want to improve the UI by adding this feature in the mobile view of the navbar, like this


![Screenshot 2024-05-10 014608](https://github.com/SamarthKadam/ChatBox/assets/124444610/5b8b25c8-b125-4cc9-9eb0-0cad3f7808e0)

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Prateek579** [comment]
hello, @parikhitritgithub  I hope these changes meet your expectations. If they're helpful, please give me the task, and I'll request to merge them
![Screenshot 2024-05-11 011311](https://github.com/SamarthKadam/ChatBox/assets/143384993/e2305803-f6a0-4a62-bd58-529bdb0b36f8)

![Screenshot 2024-05-11 011326](https://github.com/SamarthKadam/ChatBox/assets/143384993/766becfd-b365-49dd-8509-71b2be06f631)

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me 
@SamarthKadam

**Comment by parikhitritgithub** [comment]
@SamarthKadam  Thank you

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
