### ISSUE TITLE
[BUG]: Download Button is Not Dynamic according to OS of Client

### ISSUE THREAD

**Issue by Shauryacious** [SamarthKadam/ChatBox#7]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I am on a MacOS but the button is not dynamic, and it shows the symbol of Windows, rather it should say the application is not available on your device

### Steps to Reproduce

1. Go to the website with Different OS like MacOS or Linux
2. Observe the download button

### Actual Results

- Download for Windows

### Expected Results

- Not Available on your Device(if available then it should be download for macOS with apple Logo)

### Evidence

<img width="575" alt="Screenshot 2024-05-10 at 7 52 04 AM" src="https://github.com/SamarthKadam/ChatBox/assets/140061224/3266f199-edb0-4854-a469-17d3fa0226b3">

**Comment by Shauryacious** [comment]
Hey, Can you assign me this issue, You can check my website https://visioniyam.vercel.app/ It has a proper functional dynamic button on home page, i can do the same for this

<img width="573" alt="Screenshot 2024-05-10 at 8 00 42 AM" src="https://github.com/SamarthKadam/ChatBox/assets/140061224/72dd1f60-a34a-44e7-ac8b-c9877b5f3ec1">

**Comment by SamarthKadam** [comment]
@Shauryacious we are looking to build for windows and would not procced with MacOS.

**Comment by Shauryacious** [comment]
then it should say "Currently not awailable on this device" instead of the download for windows
