### ISSUE TITLE
{Enhancement]Home Page Text Animation 

### ISSUE THREAD

**Issue by Rohitha-pudu** [SamarthKadam/ChatBox#74]
### Adding a text animation can have a better User Experience
I will work on this issue.Please Assign This Issue to me

**Comment by Saigenix** [comment]
Currently UI needs to be fully responsive so I think we should focus on Responsiveness first then on animation! if  you want you can improve the UI !
Create new issue for that as I am closing this one

**Comment by Saigenix** [comment]
For Future updates
