### ISSUE TITLE
Add notification feature

### ISSUE THREAD

**Issue by mehtakevan** [SamarthKadam/ChatBox#8]
Notification feature will show all the messages you received while you are not in that chat.

**Comment by mehtakevan** [comment]
@SamarthKadam can you please assign this issue to me.

**Comment by SamarthKadam** [comment]
@mehtakevan Can you please elaborate the issue

**Comment by mehtakevan** [comment]
@SamarthKadam I was thinking in 2 ways
1)We can send an email notification about the message

2)There can be a notification icon on top right and there we can push the notification

**Comment by Stacvirus** [comment]
it would be great if I could help on this feature
