### ISSUE TITLE
BUG/ Multiple Group in single click.

### ISSUE THREAD

**Issue by abhiperfect** [SamarthKadam/ChatBox#84]
If the user clicks the 'create chat' button multiple times while creating a new group, multiple groups will be created, which is not the intended behavior.

https://github.com/SamarthKadam/ChatBox/assets/114478676/daa5d58f-6113-42e2-b3c4-2ff95f0443da

**Comment by abhiperfect** [comment]
I'm eager to work on this issue. Please assign the task to me.

**Comment by rahulm-28** [comment]
I want to work on this issue. Can you please assign me the task to me?
