### ISSUE TITLE
Add Nevigation Link to the Website Logo

### ISSUE THREAD

**Issue by MastanSayyad** [SamarthKadam/ChatBox#92]
**Minor change:** The website logo doesn't have a link to the website homepage, which is a common practice and provides users with a convenient way to navigate back to the homepage. 

![image](https://github.com/SamarthKadam/ChatBox/assets/101971980/c6928d31-34ef-4c50-9702-c12ef042108a)

@SamarthKadam  could you please assign me this issue under GSSoC'24?

**Comment by Saigenix** [comment]
You can fix that !

**Comment by hari659tri** [comment]
I want to work on this issue. Please assign me this under GSSOC24 label
