### ISSUE TITLE
Validation Message for Empty Fields on Signup/Login Page

### ISSUE THREAD

**Issue by thedarknight01** [SamarthKadam/ChatBox#98]
When users attempt to submit the Signup or Login form without filling in the required fields, they should see a validation mark indicating that these fields are required. Currently, no such marks are appearing, leading to user confusion.

![Screenshot 2024-05-17 214748](https://github.com/SamarthKadam/ChatBox/assets/95606924/eddc948d-9eb5-42ad-a4ba-664c02739f8a)

# Steps to Reproduce:

Navigate to the Signup or Login page.
Leave all fields empty.
Press the Submit button

# Actual Behavior:
No validation message appears, and the form does not indicate which fields are required.

# Expected Behavior:
A validation mark should appear next to each empty required field, indicating that the field is required. The form should not be submit. A validation message should appear next to or below each empty required field, indicating that the field is required. The form should not be submitted.ted.

**Comment by mondalsurojit** [comment]
I hope this message finds you well. I am a participant in the GirlScript Summer of Code (GSSoC) and I am very interested in contributing to this project. Could you please assign me this problem...?

**Comment by vysuvysavya** [comment]
I can fix this issue. please assign me this issue @SamarthKadam
